//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Korean.rc
//
#define IDC_APPLY                       3
#define IDD_ABOUTBOX                    100
#define IDD_MSGFORM                     101
#define IDR_TAPUR                       102
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   127
#define IDI_MAIN                        127
#define IDR_MAIN_TOOL                   127
#define IDR_TAPURTYPE                   128
#define IDD_RSF_SIMPLEFORM              129
#define IDD_FOLDERFORM                  132
#define IDD_MSGLISTFORM                 135
#define IDR_POPUP_MAIN                  137
#define STOPX                           147
#define PAUSED                          148
#define PAUSEU                          149
#define PAUSEX                          150
#define PLAYD                           151
#define PLAYU                           152
#define PLAYX                           153
#define STOPD                           154
#define STOPU                           155
#define STOPF                           156
#define PAUSEF                          157
#define PLAYF                           158
#define IDR_POPUP_TRASHCAN              168
#define IDR_POPUP_FOLDER                169
#define IDR_POPUP_SETUP                 170
#define IDI_F_MSG_CLOSE                 171
#define IDI_F_MSG_OPEN                  172
#define IDI_F_RESP_CLOSE                173
#define IDI_F_RESP_OPEN                 174
#define IDI_RESP_SIMPLE                 175
#define IDI_MSG_SIMPLE                  176
#define IDI_F_ROOT                      177
#define IDI_F_MSG_TRASH                 178
#define IDI_F_RESP_TRASH                179
#define IDD_RSF_NEW                     180
#define IDR_POPUP_SETLIST               181
#define IDD_FOLDER_NEW                  182
#define IDR_POPUP_MSGLIST               183
#define IDD_FOLDER_RENAME               184
#define IDR_POPUP_TRASH                 185
#define IDD_RSF_RENAME                  186
#define IDI_F_RESP_DRAG                 187
#define IDI_F_MSG_DRAG                  188
#define IDC_LINK                        189
#define IDD_SETTING                     190
#define IDB_TAPUR                       194
#define IDD_TAB_PUB                     195
#define IDS_FOLDER_DEF                  196
#define IDS_FOLDER_MSG                  197
#define IDI_T_RECORD                    198
#define IDS_FOLDER_TRASH                200
#define IDS_FOLDER_MSG_TRASH            201
#define IDI_T_RECORD_PAUSE              202
#define IDD_TAB_ADMIN                   203
#define IDD_CONVERT_AUDIO               205
#define IDD_TAB_REC                     206
#define IDI_NEW                         207
#define IDI_DISCON                      208
#define IDD_RSF_AUDIO                   209
#define IDS_FOLDER_SETUP                210
#define IDD_RSF_BEEP                    211
#define IDS_FOLDER_SETUP_TRASH          212
#define IDD_RSF_CHAT                    213
#define IDD_VIDEO                       214
#define IDD_CONVERT_VIDEO               215
#define IDD_TAB_VREC                    216
#define IDI_VMSG_SIMPLE                 217
#define IDD_RSF_VIDEO                   217
#define IDR_RECMOD_TOOL                 218
#define IDD_RSF_IMG                     218
#define IDR_DROP_RECMOD                 219
#define IDD_TMSGBOX                     219
#define IDD_HOTKEY                      220
#define IDI_T_RECORD_SND                221
#define IDD_RSF_PRG                     221
#define IDI_T_RECORD_BOTH               222
#define IDI_T_RECORD_RCV                223
#define IDI_T_RECORD_STOP               226
#define IDI_T_VRECORD_STOP              227
#define IDI_T_VRECORD_PAUSE             228
#define IDI_T_VRECORD                   229
#define IDI_VMSG_RECORD                 230
#define IDI_MSG_RECORD                  231
#define IDI_APP_VPLAY                   237
#define IDI_APP_PLAY                    238
#define IDI_RCV1                        239
#define IDI_RCV2                        240
#define IDS_RSF_DEF                     300
#define IDS_MSG_DEF                     400
#define IDS_MSGLIST_HEAD                450
#define IDS_RSFLIST_HEAD                451
#define IDS_HOTKEYLIST_HEAD             460
#define IDS_PANE_MSG                    501
#define IDS_PANE_SETUP                  502
#define IDS_HK_SHOW                     701
#define IDS_HK_HIDE                     702
#define IDS_HK_RECORD                   703
#define IDS_HK_VRECORD                  704
#define IDS_HK_REC_PAUSE                705
#define IDS_HK_REC_STOP                 706
#define IDS_HK_PLAY                     707
#define IDS_HK_PLAY_PAUSE               708
#define IDS_HK_PLAY_STOP                709
#define IDS_HK_PLAY_NEXT                710
#define IDS_HK_PLAY_PREV                711
#define IDC_EDIT                        1000
#define IDS_TAB_PUB                     1001
#define IDS_TAB_ADMIN                   1002
#define IDS_TAB_REC                     1003
#define IDS_TAB_VREC                    1004
#define IDC_LIST                        1005
#define IDS_TAB_REC_WARNING             1006
#define IDC_PLAY                        1007
#define IDS_TAB_RECSTOP_WARNING         1008
#define IDC_BTN_FILE                    1009
#define IDS_TAB_VREC_WARNING            1010
#define IDC_BTN_PODCAST                 1011
#define IDS_TAB_VRECSTOP_WARNING        1013
#define IDC_BTN_VFILE                   1014
#define IDC_STATIC_TITLE                1015
#define IDC_STATIC_TIME                 1016
#define IDC_STOP                        1017
#define IDC_PAUSE                       1018
#define IDC_PROGRESS                    1019
#define IDC_STATIC_ID                   1020
#define IDC_STATIC_TITLE1               1020
#define IDC_STATIC_LINKBUY              1020
#define IDC_EDIT_ID                     1021
#define IDC_STATIC_TITLE2               1021
#define IDC_STATIC_NAME                 1022
#define IDC_STATIC_TITLE3               1022
#define IDC_EDIT_FOLDER                 1023
#define IDC_STATIC_SENDER               1023
#define IDC_STATIC_SENDER_ID            1023
#define IDC_STATIC_NAME2                1023
#define IDC_APP_PLAY                    1024
#define IDC_STATIC_NAME3                1024
#define IDC_EDIT_NAME                   1025
#define IDC_STATIC_DATE                 1025
#define IDC_STATIC_NAME4                1025
#define IDC_STATIC2                     1026
#define IDC_STATIC_TITLE111             1026
#define IDC_STATIC_TITLE4               1026
#define IDC_STATIC_NAME5                1026
#define IDC_TAB                         1027
#define IDC_STATIC_SENDER2              1027
#define IDC_STATIC_SENDER_NAME          1027
#define IDC_STATIC_NAME6                1027
#define IDC_APP_VPLAY                   1028
#define IDC_STATIC_NAME7                1028
#define IDC_CHK_MUTE                    1029
#define IDC_STATIC_NAME8                1029
#define IDC_CHK_CONTACT                 1030
#define IDC_STATIC_NAME9                1030
#define IDC_CHK_DISABLE                 1031
#define IDC_STATIC_NAME10               1031
#define IDC_CMB_MAX_RECORD              1032
#define IDC_STATIC1                     1033
#define IDC_STATIC3                     1034
#define IDC_CMB_WAIT_ANSWER             1035
#define IDC_STATIC8                     1035
#define IDC_CMB_VRECORD_LIMIT           1036
#define IDC_STATIC9                     1036
#define IDC_STATIC4                     1037
#define IDC_CMB_CMP                     1037
#define IDC_STATIC10                    1037
#define IDC_FRAME2                      1038
#define IDC_CMB_FPS                     1038
#define IDC_STATIC5                     1039
#define IDC_CHK_STARTUP                 1039
#define IDC_FRAME1                      1040
#define IDC_STATIC6                     1041
#define IDC_FRAME5                      1041
#define IDC_FRM_MSG_FOLDER              1041
#define IDC_BTN_BEEPFILE                1042
#define IDC_FRM_SKYPE_PORT              1042
#define IDC_STATIC7                     1043
#define IDC_FRAME6                      1043
#define IDC_FRAME3                      1044
#define IDC_FRAME4                      1045
#define IDC_STATIC_COPY                 1046
#define IDC_CHK_LOG                     1047
#define IDC_STATIC_COPY3                1047
#define IDC_STATIC_COPY2                1048
#define IDC_CHK_DATAPATH                1048
#define IDC_CMB_ID                      1049
#define IDC_CHK_HOTKEY                  1049
#define IDC_BROWSETARGET                1050
#define IDC_CMB_PRGARG2                 1050
#define IDC_STATIC_COPY4                1050
#define IDC_TARGET                      1051
#define IDC_CMB_PRGARG3                 1051
#define IDC_EDIT_REC_WARNING            1052
#define IDC_CMB_PRGARG4                 1052
#define IDC_BTN_REC_WARNING             1053
#define IDC_CMB_PRGARG5                 1053
#define IDC_EDIT_RECSTOP_WARNING        1054
#define IDC_CMB_PRGARG7                 1054
#define IDC_RDO_REC                     1055
#define IDC_CMB_PRGARG8                 1055
#define IDC_BTN_RECSTOP_WARNING         1056
#define IDC_CMB_PRGARG9                 1056
#define IDC_RDO_VREC                    1057
#define IDC_CMB_PRGARG10                1057
#define IDC_EDIT_VREC_WARNING           1058
#define IDC_CHK_AUDIO                   1059
#define IDC_RDO_MONORAL                 1060
#define IDC_BTN_VREC_WARNING            1061
#define IDC_BTN_AUDIO                   1062
#define IDC_RDO_STEREO                  1063
#define IDC_RDO_STEREO1                 1063
#define IDC_EDIT_VRECSTOP_WARNING       1064
#define IDC_RDO_STEREO2                 1064
#define IDC_RDO_DISCONNECT              1065
#define IDC_BTN_VRECSTOP_WARNING        1066
#define IDC_CHK_CHAT                    1067
#define IDC_BTN_CHAT                    1068
#define IDC_CHK_IMG                     1069
#define IDC_PICT                        1069
#define IDC_BTN_IMG                     1070
#define IDC_EDIT_TITLE                  1070
#define IDC_CHK_VIDEO                   1071
#define IDC_BTN_VIDEO                   1072
#define IDC_CHK_BEEP                    1073
#define IDC_PIC_FRAME                   1073
#define IDC_ST_SIZE_AUDIO               1074
#define IDC_RDO_NOCMP                   1074
#define IDC_ST_SIZE_CHAT                1075
#define IDC_RDO_CMP                     1075
#define IDC_EDIT_CHAT                   1076
#define IDC_ST_SIZE_VIDEO               1076
#define IDC_CHK_TMSGBOX                 1076
#define IDC_VIDEOGRAB                   1077
#define IDC_ST_SIZE_IMG                 1077
#define IDC_STATIC_TMSGBOX              1077
#define IDC_CHK_NOAUDIO                 1078
#define IDC_STATIC_SRC                  1078
#define IDC_CHK_PRG                     1078
#define IDC_CMB_RECORD_LIMIT            1079
#define IDC_BTN_PRG                     1079
#define IDC_CHK_VSETTOP                 1080
#define IDC_BROWSE_DATAPATH             1080
#define IDC_DATAPATH                    1081
#define IDC_CHK_RECSTOP_WARNING         1082
#define IDC_BTN_HOTKEY                  1082
#define IDC_CHK_REC_WARNING             1083
#define IDC_CHK_VREC_WARNING            1084
#define IDC_CHK_VRECSTOP_WARNING        1085
#define IDC_EDIT_SKYPE_PORT_OUT         1086
#define IDC_EDIT_SKYPE_PORT_MIC         1087
#define IDC_RDO_WAV                     1088
#define IDC_RDO_OGG                     1089
#define IDC_RDO_MP3                     1090
#define IDC_CMB_CODEC                   1091
#define IDC_CMB_FORMAT                  1092
#define IDC_GRP_STEREO                  1093
#define IDC_GRP_TYPE                    1094
#define IDC_HOTKEY1                     1096
#define IDC_LIST_HOTKEY                 1098
#define IDS_TAB_CHECK                   1100
#define IDC_CMB_PRG                     1103
#define IDC_EDIT_PRGPATH                1105
#define IDC_CMB_PRGARG1                 1106
#define IDC_CMB_PRGARG6                 1107
#define IDC_CHK_AUTO_ENABLE             1107
#define IDC_CMB_TMSGBOX                 1109
#define IDS_RSF_PRG1                    2001
#define IDS_RSF_PRG901                  2901
#define IDS_RSF_ARG_AUDIOFILE           3001
#define IDS_RSF_ARG_VIDEOFILE           3002
#define IDS_RSF_ARG_CALLERID            3003
#define IDS_RSF_ARG_CALLERNAME          3004
#define IDS_RSF_ARG_MYID                3005
#define IDS_RSF_ARG_MYNAME              3006
#define IDS_RSF_ARG_CALLERADDRESS       3007
#define IDS_RSF_ARG_CALLERPHONEHOME     3008
#define IDS_RSF_ARG_CALLERPHONEOFFICE   3009
#define IDS_RSF_ARG_CALLERPHONEMOBILE   3010
#define IDS_CAPTION_CON                 5001
#define IDS_CAPTION_DISCON              5002
#define IDS_CAPTION                     5003
#define IDS_CAPTION_DISABLE             5004
#define IDS_TOOLTIP                     5101
#define IDS_TOOLTIP_DISABLE             5102
#define IDS_TOOLTIP_DISCON              5103
#define IDS_TOOLTIP_NEW                 5104
#define IDS_TOOLTIP_RCV                 5105
#define IDS_TOOLTIP_REC                 5106
#define IDS_TOOLTIP_DISABLE2            5107
#define IDS_TOOLTIP_AUTO_ENABLE         5108
#define IDS_URL_HELP                    9001
#define IDS_URL_SKYPE                   9002
#define IDS_URL_AUDACITY                9005
#define IDS_URL_LAME                    9006
#define IDS_URL_LINKBUY                 9010
#define IDS_URL_DONATION                9015
#define IDS_MSGBOX0                     10000
#define IDS_MSGBOX1                     10001
#define IDS_MSGBOX2                     10002
#define IDS_MSGBOX3                     10003
#define IDS_MSGBOX4                     10004
#define IDS_MSGBOX5                     10005
#define IDS_MSGBOX6                     10006
#define IDS_MSGBOX7                     10007
#define IDS_MSGBOX8                     10008
#define IDS_MSGBOX9                     10009
#define IDS_MSGBOX10                    10010
#define IDS_MSGBOX11                    10011
#define IDS_MSGBOX12                    10012
#define IDS_MSGBOX13                    10013
#define IDS_MSGBOX14                    10014
#define IDS_MSGBOX15                    10015
#define IDS_MSGBOX16                    10016
#define IDS_MSGBOX17                    10017
#define IDS_MSGBOX18                    10018
#define IDS_MSGBOX21                    10021
#define IDS_MSGBOX22                    10022
#define IDS_MSGBOX23                    10023
#define IDS_MSGBOX31                    10031
#define IDS_MSGBOX32                    10032
#define IDS_MSGBOX33                    10033
#define IDS_MSGBOX34                    10034
#define IDS_MSGBOX41                    10041
#define IDS_MSGBOX42                    10042
#define IDS_MSGBOX51                    10051
#define IDS_MSGBOX52                    10052
#define IDS_MSGBOX53                    10053
#define IDS_MSGBOX54                    10054
#define IDS_MSGBOX58                    10058
#define IDS_MSGBOX59                    10059
#define IDS_MSGBOX60                    10060
#define IDS_MSGBOX61                    10061
#define IDS_MSGBOX62                    10062
#define IDS_MSGBOX63                    10063
#define IDS_MSGBOX64                    10064
#define IDS_MSGBOX65                    10065
#define IDS_MSGBOX66                    10066
#define IDS_MSGBOX67                    10067
#define IDS_MSGBOX68                    10068
#define IDS_MSGBOX69                    10069
#define IDS_MSGBOX70                    10070
#define IDS_MSGBOX71                    10071
#define IDS_MSGBOX72                    10072
#define IDS_MSGBOX73                    10073
#define IDS_MSGBOX74                    10074
#define IDS_MSGBOX75                    10075
#define IDS_MSGBOX76                    10076
#define IDS_MSGBOX77                    10077
#define IDS_MSGBOX78                    10078
#define IDS_MSGBOX79                    10079
#define IDS_MSGBOX81                    10081
#define IDS_MSGBOX82                    10082
#define IDS_MSGBOX83                    10083
#define IDS_MSGBOX84                    10084
#define IDS_MSGBOX85                    10085
#define IDS_MSGBOX86                    10086
#define IDS_MSGBOX87                    10087
#define IDS_MSGBOX88                    10088
#define IDS_MSGBOX89                    10089
#define IDS_MSGBOX90                    10090
#define IDS_MSGBOX91                    10091
#define IDS_MSGBOX101                   10101
#define IDS_MSGBOX102                   10102
#define IDS_MSGBOX106                   10106
#define IDS_MSGBOX107                   10107
#define IDS_MSGBOX111                   10111
#define IDS_MSGBOX112                   10112
#define IDS_MSGBOX115                   10115
#define IDS_MSGBOX121                   10121
#define IDS_MSGBOX801                   10801
#define IDS_MSGBOX900                   10900
#define IDS_MSGBOX901                   10901
#define IDS_TMSGBOX_TITLE1              20000
#define IDS_TMSGBOX_TITLE2              20001
#define IDS_TMSGBOX_MSG1                20010
#define IDS_TMSGBOX_MSG2                20011
#define IDS_REPAIR_TITLE                20100
#define IDS_REPAIR_MSG                  20101
#define IDS_REPAIR_DATA                 20102
#define IDS_REPAIR_NAME                 20103
#define ID_POPUP_OPEN                   32771
#define ID_POPUP_ENABLE                 32772
#define ID_POPUP_CLOSE                  32773
#define ID_POPUP_SETUP_NEW              32774
#define ID_POPUP_FOLDER_NEW             32775
#define ID_POPUP_FOLDER_RENAME          32776
#define ID_POPUP_FOLDER_DEL             32777
#define ID_POPUP_TRASH_CLEAR            32778
#define ID_POPUP_TRASHCAN_CLEAR         32779
#define ID_POPUP_SETLIST_DEL            32780
#define ID_POPUP_SETLIST_PLAY           32781
#define ID_POPUP_MSGLIST_PLAY           32782
#define ID_POPUP_MSGLIST_CALL           32782
#define ID_POPUP_MSGLIST_DEL            32783
#define ID_POPUP_TRASH_UNDO             32785
#define ID_POPUP_TRASH_RECOVER          32785
#define ID_POPUP_SETLIST_NEW            32787
#define ID_POPUP_SETLIST_RENAME         32788
#define ID_POPUP_MSGLIST_SETUP          32789
#define ID_POPUP_SETLIST_CALL           32790
#define ID_POPUP_SETLIST_COPY           32791
#define ID_POPUP_SETLIST_PASTE          32792
#define ID_TOOL_SETTING                 32793
#define ID_DUMMY                        32794
#define ID_RECORD_START                 32795
#define ID_RECORD_PAUSE                 32796
#define ID_PLACEHOLDER                  32797
#define ID_RECORD_STOP                  32798
#define ID_TOOL_RECORD                  32799
#define ID_TOOL_RECPAUSE                32800
#define ID_TOOL_RECSTOP                 32801
#define ID_APP_HELP                     32802
#define ID_VRECORD_START                32803
#define ID_RECMOD_BOTH                  32805
#define ID_RECMOD_RCV                   32806
#define ID_RECMOD_SND                   32807
#define ID_RECORD_MOD                   32808
#define ID_APP_PLAY                     32809
#define ID_APP_VPLAY                    32810
#define ID_POPUP_STOP                   32810
#define ID_APP_SKYPE                    32811
#define ID_AUDIO_FOLDER                 32812
#define ID_VIDEO_FOLDER                 32813
#define ID_SOUND_RECORDER               32814
#define ID_REPAIR                       32816
#define ID_AUDACITY                     32818
#define ID_DONATION                     32820
#define ID_MP3_FOLDER                   32822
#define ID_WAV_FOLDER                   32823
#define ID_LINK_LAME                    32825
#define ID_POPUP_AUTO_ENABLE            32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
