//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Japanese.rc
//
#define IDC_APPLY                       3
#define IDD_ABOUTBOX                    100
#define IDD_MSGFORM                     101
#define IDR_TAPUR                       102
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   127
#define IDI_MAIN                        127
#define IDR_MAIN_TOOL                   127
#define IDR_TAPURTYPE                   128
#define IDD_RSFSIMPLEFORM               129
#define IDD_RSF_SIMPLEFORM              129
#define IDD_FOLDERFORM                  132
#define IDD_MSGLISTFORM                 135
#define IDR_POPUP_MAIN                  137
#define STOPX                           147
#define PAUSED                          148
#define PAUSEU                          149
#define PAUSEX                          150
#define PLAYD                           151
#define PLAYU                           152
#define PLAYX                           153
#define STOPD                           154
#define STOPU                           155
#define STOPF                           156
#define PAUSEF                          157
#define PLAYF                           158
#define IDR_POPUP_TRASHCAN              168
#define IDR_POPUP_FOLDER                169
#define IDR_POPUP_SETUP                 170
#define IDI_F_MSG_CLOSE                 171
#define IDI_F_MSG_OPEN                  172
#define IDI_F_RESP_CLOSE                173
#define IDI_F_RESP_OPEN                 174
#define IDI_RESP_SIMPLE                 175
#define IDI_MSG_SIMPLE                  176
#define IDI_F_ROOT                      177
#define IDI_F_MSG_TRASH                 178
#define IDI_F_RESP_TRASH                179
#define IDD_RSF_NEW                     180
#define IDR_POPUP_SETLIST               181
#define IDD_FOLDER_NEW                  182
#define IDR_POPUP_MSGLIST               183
#define IDD_FOLDER_RENAME               184
#define IDR_POPUP_TRASH                 185
#define IDD_RSF_RENAME                  185
#define IDI_F_RESP_DRAG                 185
#define IDI_F_MSG_DRAG                  186
#define IDC_LINK                        187
#define IDD_SETTING                     190
#define IDB_TAPUR                       194
#define IDD_TAB_PUB                     195
#define IDS_FOLDER_DEF                  200
#define IDS_FOLDER_MSG                  200
#define IDI_T_RECORD                    200
#define IDS_FOLDER_TRASH                201
#define IDS_FOLDER_MSG_TRASH            201
#define IDI_T_RECORD_PAUSE              202
#define IDD_TAB_ADMIN                   203
#define IDD_CONVERT_AUDIO               205
#define IDD_TAB_REC                     206
#define IDI_NEW                         207
#define IDI_DISCON                      208
#define IDD_RSF_AUDIO                   209
#define IDS_FOLDER_SETUP                210
#define IDD_RSF_BEEP                    210
#define IDS_FOLDER_SETUP_TRASH          211
#define IDD_RSF_CHAT                    211
#define IDD_VIDEO                       212
#define IDD_CONVERT_VIDEO               213
#define IDD_TAB_VREC                    214
#define IDI_VMSG_SIMPLE                 216
#define IDR_RECMOD_TOOL                 217
#define IDR_DROP_RECMOD                 219
#define IDI_T_RECORD_SND                221
#define IDI_T_RECORD_BOTH               222
#define IDI_T_RECORD_RCV                223
#define IDI_T_RECORD_STOP               226
#define IDI_T_VRECORD_STOP              227
#define IDI_T_VRECORD_PAUSE             228
#define IDI_T_VRECORD                   229
#define IDI_VMSG_RECORD                 230
#define IDI_MSG_RECORD                  231
#define IDI_APP_VPLAY                   237
#define IDI_APP_PLAY                    238
#define IDS_RSF_DEF                     300
#define IDS_MSG_DEF                     400
#define IDC_EDIT                        1000
#define IDS_TAB_PUB                     1000
#define IDS_TAB_ADMIN                   1001
#define IDS_TAB_REC                     1002
#define IDS_TAB_VREC                    1003
#define IDC_LIST                        1004
#define IDS_TAB_REC_WARNING             1010
#define IDC_PLAY                        1011
#define IDS_TAB_RECSTOP_WARNING         1011
#define IDC_BTN_FILE                    1012
#define IDS_TAB_VREC_WARNING            1012
#define IDC_BTN_PODCAST                 1013
#define IDS_TAB_VRECSTOP_WARNING        1013
#define IDC_BTN_VFILE                   1014
#define IDC_STATIC_TITLE                1015
#define IDC_STATIC_TIME                 1016
#define IDC_STOP                        1017
#define IDC_PAUSE                       1018
#define IDC_PROGRESS                    1019
#define IDC_STATIC_ID                   1020
#define IDC_EDIT_ID                     1021
#define IDC_STATIC_NAME                 1022
#define IDC_EDIT_FOLDER                 1022
#define IDC_APP_PLAY                    1022
#define IDC_EDIT_NAME                   1023
#define IDC_STATIC2                     1023
#define IDC_TAB                         1023
#define IDC_APP_VPLAY                   1023
#define IDC_CHK_MUTE                    1025
#define IDC_CHK_CONTACT                 1026
#define IDC_CHK_DISABLE                 1027
#define IDC_CMB_MAX_RECORD              1029
#define IDC_STATIC1                     1030
#define IDC_STATIC3                     1031
#define IDC_CMB_WAIT_ANSWER             1032
#define IDC_CMB_VRECORD_LIMIT           1032
#define IDC_STATIC4                     1033
#define IDC_FRAME2                      1034
#define IDC_STATIC5                     1034
#define IDC_FRAME1                      1035
#define IDC_STATIC6                     1035
#define IDC_BTN_BEEPFILE                1036
#define IDC_STATIC7                     1036
#define IDC_FRAME3                      1037
#define IDC_FRAME4                      1038
#define IDC_STATIC_COPY                 1040
#define IDC_CHK_LOG                     1041
#define IDC_STATIC_COPY2                1041
#define IDC_CMB_ID                      1043
#define IDC_BROWSETARGET                1044
#define IDC_TARGET                      1045
#define IDC_EDIT_REC_WARNING            1047
#define IDC_BTN_REC_WARNING             1048
#define IDC_EDIT_RECSTOP_WARNING        1049
#define IDC_RDO_REC                     1049
#define IDC_BTN_RECSTOP_WARNING         1050
#define IDC_RDO_VREC                    1050
#define IDC_EDIT_VREC_WARNING           1051
#define IDC_CHK_AUDIO                   1051
#define IDC_RDO_MONORAL                 1051
#define IDC_BTN_VREC_WARNING            1052
#define IDC_BTN_AUDIO                   1052
#define IDC_RDO_STEREO                  1052
#define IDC_EDIT_VRECSTOP_WARNING       1053
#define IDC_RDO_DISCONNECT              1053
#define IDC_BTN_VRECSTOP_WARNING        1054
#define IDC_CHK_CHAT                    1054
#define IDC_BTN_CHAT                    1055
#define IDC_CHK_IMG                     1056
#define IDC_BTN_IMG                     1057
#define IDC_CHK_VIDEO                   1058
#define IDC_BTN_VIDEO                   1059
#define IDC_CHK_BEEP                    1060
#define IDC_ST_SIZE_AUDIO               1061
#define IDC_ST_SIZE_CHAT                1062
#define IDC_EDIT_CHAT                   1062
#define IDC_VIDEOGRAB                   1064
#define IDC_CHK_NOAUDIO                 1065
#define IDC_CMB_RECORD_LIMIT            1067
#define IDC_CHK_VSETTOP                 1068
#define IDS_CAPTION_CON                 5001
#define IDS_CAPTION_DISCON              5002
#define IDS_CAPTION                     5003
#define IDS_CAPTION_DISABLE             5004
#define IDS_TOOLTIP                     5101
#define IDS_TOOLTIP_DISABLE             5102
#define IDS_TOOLTIP_DISCON              5103
#define IDS_TOOLTIP_NEW                 5104
#define IDS_URL_HELP                    9001
#define IDS_URL_SKYPE                   9002
#define IDS_MSGBOX0                     10000
#define IDS_MSGBOX1                     10001
#define IDS_MSGBOX2                     10002
#define IDS_MSGBOX3                     10003
#define IDS_MSGBOX4                     10004
#define IDS_MSGBOX5                     10005
#define IDS_MSGBOX6                     10006
#define IDS_MSGBOX7                     10007
#define IDS_MSGBOX8                     10008
#define IDS_MSGBOX9                     10009
#define IDS_MSGBOX10                    10010
#define IDS_MSGBOX11                    10011
#define IDS_MSGBOX12                    10012
#define IDS_MSGBOX13                    10013
#define IDS_MSGBOX14                    10014
#define IDS_MSGBOX15                    10015
#define IDS_MSGBOX16                    10016
#define IDS_MSGBOX17                    10017
#define IDS_MSGBOX18                    10018
#define IDS_MSGBOX21                    10021
#define IDS_MSGBOX22                    10022
#define IDS_MSGBOX23                    10023
#define IDS_MSGBOX31                    10031
#define IDS_MSGBOX32                    10032
#define IDS_MSGBOX33                    10033
#define IDS_MSGBOX34                    10034
#define IDS_MSGBOX41                    10041
#define IDS_MSGBOX42                    10042
#define IDS_MSGBOX51                    10051
#define IDS_MSGBOX52                    10052
#define IDS_MSGBOX53                    10053
#define IDS_MSGBOX54                    10054
#define IDS_MSGBOX60                    10060
#define IDS_MSGBOX61                    10061
#define IDS_MSGBOX62                    10062
#define IDS_MSGBOX63                    10063
#define IDS_MSGBOX64                    10064
#define IDS_MSGBOX69                    10069
#define IDS_MSGBOX70                    10070
#define IDS_MSGBOX71                    10071
#define IDS_MSGBOX72                    10072
#define IDS_MSGBOX73                    10073
#define IDS_MSGBOX74                    10074
#define IDS_MSGBOX75                    10075
#define IDS_MSGBOX76                    10076
#define IDS_MSGBOX77                    10077
#define IDS_MSGBOX81                    10081
#define IDS_MSGBOX82                    10082
#define IDS_MSGBOX83                    10083
#define IDS_MSGBOX84                    10084
#define IDS_MSGBOX85                    10085
#define IDS_MSGBOX86                    10086
#define IDS_MSGBOX88                    10088
#define IDS_MSGBOX89                    10089
#define IDS_MSGBOX90                    10090
#define IDS_MSGBOX91                    10091
#define IDS_MSGBOX101                   10101
#define IDS_MSGBOX102                   10102
#define IDS_MSGBOX900                   10900
#define IDS_MSGBOX901                   10901
#define ID_POPUP_OPEN                   32771
#define ID_POPUP_ENABLE                 32772
#define ID_POPUP_CLOSE                  32773
#define ID_POPUP_SETUP_NEW              32774
#define ID_POPUP_FOLDER_NEW             32775
#define ID_POPUP_FOLDER_RENAME          32776
#define ID_POPUP_FOLDER_DEL             32777
#define ID_POPUP_TRASH_CLEAR            32778
#define ID_POPUP_TRASHCAN_CLEAR         32779
#define ID_POPUP_SETLIST_DEL            32780
#define ID_POPUP_SETLIST_PLAY           32781
#define ID_POPUP_MSGLIST_PLAY           32782
#define ID_POPUP_MSGLIST_CALL           32782
#define ID_POPUP_MSGLIST_DEL            32783
#define ID_POPUP_TRASH_UNDO             32785
#define ID_POPUP_TRASH_RECOVER          32785
#define ID_POPUP_SETLIST_NEW            32787
#define ID_POPUP_SETLIST_RENAME         32788
#define ID_POPUP_MSGLIST_SETUP          32789
#define ID_POPUP_SETLIST_CALL           32790
#define ID_POPUP_SETLIST_COPY           32791
#define ID_POPUP_SETLIST_PASTE          32792
#define ID_TOOL_SETTING                 32793
#define ID_DUMMY                        32794
#define ID_RECORD_START                 32795
#define ID_RECORD_PAUSE                 32796
#define ID_PLACEHOLDER                  32797
#define ID_RECORD_STOP                  32798
#define ID_TOOL_RECORD                  32799
#define ID_TOOL_RECPAUSE                32800
#define ID_TOOL_RECSTOP                 32801
#define ID_APP_HELP                     32802
#define ID_VRECORD_START                32803
#define ID_RECMOD_BOTH                  32805
#define ID_RECMOD_RCV                   32806
#define ID_RECMOD_SND                   32807
#define ID_RECORD_MOD                   32808
#define ID_APP_PLAY                     32809
#define ID_APP_VPLAY                    32810
#define ID_APP_SKYPE                    32811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
